### ISSUE TITLE
Add "hacktoberfest" topic to repo

### ISSUE THREAD

**Issue by cperthel** [PedroJM96/SuperLobbyDeluxe#1]
Hi @PedroJM96,

do you mind adding the "hacktoberfest" topic to this repo please?
I am sure there is something the community can contribute to this plugin.

More info on Hacktoberfest:
https://hacktoberfest.com/participation/#maintainers

Many Projects already opted in to Hacktoberfest:
https://github.com/topics/hacktoberfest

**Comment by PedroJM96** [comment]
Done, added friend.
