### ISSUE TITLE
location.world

### ISSUE THREAD

**Issue by jefflima1** [PedroJM96/SuperLobbyDeluxe#17]
Hello, I'll try to describe the problem, I'm migrating from the multiverse core, to myworlds, I use the superlobby in a survival world, but I have a separate world as "lobby" I set the settings correctly, players who enter for the first time enter the world lobby, etc... however when the multiverse is installed the "void-tp" option of the superlobby works correctly, when I remove the multiverse, once the player falls into void, from the lobby itself, or from the end, " I put it in the superlobby configuration to pull the player" the error below appears, going to the "lobby" and typing / sl setspawn , the "void-tp" works correctly, however you have to type it each time the server is restarted, however when multiverse is installed, it is not necessary to type the command each time it restarts, without multiverse installed, the error occurs, and the "void-tp" function does not work.

Version: SuperLobbyDeluxe 4.6.0

[21:42:39 ERRO]: Unable to pass event PlayerMoveEvent for SuperLobby v4.6.0
java.lang.IllegalArgumentException: location.world
em com.google.common.base.Preconditions.checkArgument(Preconditions.java:145) ~[guava-31.1-jre.jar:?]
em org.bukkit.craftbukkit.v1_19_R3.entity.CraftPlayer.teleport(CraftPlayer.java:1340) ~[purpur-1.19.4.jar:git-Purpur-1976]
em org.bukkit.craftbukkit.v1_19_R3.entity.CraftPlayer.teleport(CraftPlayer.java:1272) ~[purpur-1.19.4.jar:git-Purpur-1976]
em org.bukkit.craftbukkit.v1_19_R3.entity.CraftEntity.teleport(CraftEntity.java:564) ~[purpur-1.19.4.jar:git-Purpur-1976]
em com.pedrojm96.superlobby.SuperLobby.teleportToSpawn(SuperLobby.java:466) ~[?:?]
em com.pedrojm96.superlobby.listener.PlayerListener.onVoidTP(PlayerListener.java:382) ~[?:?]
em com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor666.execute(Unknown Source) ~[?:?]
em org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
em co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:git-Purpur-1976]
em org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
em io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.19.4.jar:git-Purpur-1976]
em io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.19.4.jar:git-Purpur-1976]
em org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
em net.minecraft.server.network.ServerGamePacketListenerImpl.handleMovePlayer(ServerGamePacketListenerImpl.java:1674) ~[?:?]
em net.minecraft.network.protocol.game.ServerboundMovePlayerPacket.handle(ServerboundMovePlayerPacket.java:29) ~[?:?]
em net.minecraft.network.protocol.game.ServerboundMovePlayerPacket$Pos.handle(ServerboundMovePlayerPacket.java:66) ~[?:?]
em net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
em net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.19.4.jar:git-Purpur-1976]
em net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
em net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
em net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1369) ~[purpur-1.19.4.jar:git-Purpur-1976]
em net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[purpur-1.19.4.jar:git-Purpur-1976]
em net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
em net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1346) ~[purpur-1.19.4.jar:git-Purpur-1976]
em net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1339) ~[purpur-1.19.4.jar:git-Purpur-1976]
em net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
em net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1317) ~[purpur-1.19.4.jar:git-Purpur-1976]
em net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1205) ~[purpur-1.19.4.jar:git-Purpur-1976]
em net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:325) ~[purpur-1.19.4.jar:git-Purpur-1976]

**Comment by PedroJM96** [comment]
Delete the spaw.yml file and set it up again with the /set spawn command.
