### ISSUE TITLE
Spawn command not displaying in tabcomplete

### ISSUE THREAD

**Issue by CDiazF4** [PedroJM96/SuperLobbyDeluxe#20]
Hi! Im using this plugin on paper 1.19.4 # 550.

The spawn command is not registered to tabcomplete, users can execute the command but is not displaying the tabcomplete.

Hope there is a fix for this.

Thank u in advance

**Comment by CDiazF4** [comment]
Forgot to mention that Im using the latest version of SuperLobbyDeluxe (4.6.2)

Thanks

**Comment by PedroJM96** [comment]
Fixed in version 4.6.6 onwards
