### ISSUE TITLE
The repo of CoreLibBukkit on maven is give me a issue

### ISSUE THREAD

**Issue by ImNacho** [PedroJM96/SuperLobbyDeluxe#5]
What happens is that I cloned the repo to edit it a bit, but the CoreLibBukkit repository is giving me a problem because it says it can't find it, can you help me with that please, here is an image of the error

https://prnt.sc/7ByHEoa5eL0N

**Comment by PedroJM96** [comment]
First you have to build the CoreLibBukkit repository: https://github.com/PedroJM96/CoreLibBukkit

**Comment by ImNacho** [comment]
But CoreLibBukkit have an issue in SuperStatsApi https://prnt.sc/PkeY57GEf7Bg

**Comment by PedroJM96** [comment]
Modify the CoreLibBukkit code and remove any methods that reference SuperStats, or download SuperStats and add it as a manual dependency in the Build Path
