### ISSUE TITLE
ItemJoin (Using hex color in item / Command not working)

### ISSUE THREAD

**Issue by Biutix** [PedroJM96/SuperLobbyDeluxe#6]
I can by hex color in the item

but the command he should run does not work

to the hex color remover it works

items.yml - example

 not working
profile:
  name: '<#bfff00> teste &7(teste' <- error (<#bfff00>)
  material: 'PLAYER_HEAD:3'
  lore:
  - '&7Clique com o botão direito para ver seu perfil'
  slot: 5
  skull: <player>
  commands:
  - 'player: profile'
  delay: 1
  permission: superlobby.items.profile

working
profile:
  name: '&ateste &7(teste)'
  material: 'PLAYER_HEAD:3'
  slot: 8
  skull: <player>
  commands:
  - 'player: profile'
  delay: 5
  permission: 'superlobby.items.game'

**Comment by PedroJM96** [comment]
What version are you using?
Hexadecimal colors are only available in minecraft from version 1.16 onwards.

**Comment by Biutix** [comment]
1.18.2

**Comment by Biutix** [comment]
color applies to item name
however when using hex color on the item it does not execute the command

**Comment by Maxcension** [comment]
Same problem for me on 1.16.5.
When applying hex color to an item, it doesn't execute the command anymore.

**Comment by Maxcension** [comment]
Also, RGB/HEx doesn't seem to work on the join title.

**Comment by PedroJM96** [comment]
Fixed in the new version
