### ISSUE TITLE
Players can cause damages to other players

### ISSUE THREAD

**Issue by moonEEVEEXwX** [PedroJM96/SuperLobbyDeluxe#9]
When 1 year ago we use Spigot 1.16.5 and SuperLobbyDeluxe4.3.3(Proxy:Waterfall(Bungeecord)),The PVP was off and no damage can be cause by anything.But when we update our server to Paper 1.17.1 and SuperLobbyDeluxe4.5.5(Proxy:Velocity),The PVP suddenly opened.I don't know is this is a SuperLobbyDeluxe error or something.But no error in the server showed up so we can't give any information to you.

**Comment by PedroJM96** [comment]
Check the worlds in the "disable-damage" setting and that "use-spawn-radius" is set to false.

**Comment by moonEEVEEXwX** [comment]
> Check the worlds in the "disable-damage" setting and that "use-spawn-radius" is set to false.

Thanks for the help but I checked the settings.yml and they are all set to false.

**Comment by Funasitien** [comment]
Yeah, I have the same issue. Everything in the config is good but it dosn't work. I use Paper 1.17.1 (and after I tried with Bungee and I got the same issue.)

**Comment by PedroJM96** [comment]
The plugin was tested in version 1.17.1 of PAPERMC and it does not present any problem. I invite you to try the plugin without any other plugin.
